-- Mustafa Kids - Supabase Database Schema

-- 1. categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text UNIQUE NOT NULL
);

-- Enable RLS and select policies
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read" ON public.categories;
CREATE POLICY "Allow public read" ON public.categories FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow all for authenticated" ON public.categories;
CREATE POLICY "Allow all for authenticated" ON public.categories FOR ALL USING (true);

-- 2. products Table
CREATE TABLE IF NOT EXISTS public.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint REFERENCES public.categories(id) ON DELETE CASCADE NOT NULL,
    name text NOT NULL,
    description text,
    price numeric NOT NULL,
    sizes text,
    image_url text,
    stock integer DEFAULT 10,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read" ON public.products;
CREATE POLICY "Allow public read" ON public.products FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow all for authenticated" ON public.products;
CREATE POLICY "Allow all for authenticated" ON public.products FOR ALL USING (true);

-- 3. orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name text NOT NULL,
    customer_phone text NOT NULL,
    address text NOT NULL,
    delivery_method text DEFAULT 'delivery'::text,
    total_amount numeric NOT NULL,
    status text DEFAULT 'Yangi'::text,
    telegram_id bigint,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public insert" ON public.orders;
CREATE POLICY "Allow public insert" ON public.orders FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow read own orders" ON public.orders;
CREATE POLICY "Allow read own orders" ON public.orders FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow all for authenticated" ON public.orders;
CREATE POLICY "Allow all for authenticated" ON public.orders FOR ALL USING (true);

-- 4. order_items Table
CREATE TABLE IF NOT EXISTS public.order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
    product_id bigint REFERENCES public.products(id) ON DELETE RESTRICT NOT NULL,
    size text,
    quantity integer DEFAULT 1,
    price numeric NOT NULL
);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public insert" ON public.order_items;
CREATE POLICY "Allow public insert" ON public.order_items FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow read own order items" ON public.order_items;
CREATE POLICY "Allow read own order items" ON public.order_items FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow all for authenticated" ON public.order_items;
CREATE POLICY "Allow all for authenticated" ON public.order_items FOR ALL USING (true);

-- 5. admin_users Table
CREATE TABLE IF NOT EXISTS public.admin_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text UNIQUE NOT NULL,
    telegram_id bigint,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow read" ON public.admin_users;
CREATE POLICY "Allow read" ON public.admin_users FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow all for authenticated" ON public.admin_users;
CREATE POLICY "Allow all for authenticated" ON public.admin_users FOR ALL USING (true);

-- 6. scheduled_videos Table
CREATE TABLE IF NOT EXISTS public.scheduled_videos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_url text NOT NULL,
    instagram_video_url text,
    caption text NOT NULL,
    hashtags text,
    scheduled_at timestamp with time zone NOT NULL,
    is_posted boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.scheduled_videos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow read" ON public.scheduled_videos;
CREATE POLICY "Allow read" ON public.scheduled_videos FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow all for authenticated" ON public.scheduled_videos;
CREATE POLICY "Allow all for authenticated" ON public.scheduled_videos FOR ALL USING (true);

-- 7. bot_users Table
CREATE TABLE IF NOT EXISTS public.bot_users (
    telegram_id bigint PRIMARY KEY,
    username text,
    first_name text NOT NULL,
    referred_by bigint,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.bot_users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read and write" ON public.bot_users;
CREATE POLICY "Allow public read and write" ON public.bot_users FOR ALL USING (true);
